---
downloads: ~/.ansible-downloads/

configure_sudoers: yes

#dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
#dotfiles_repo_accept_hostkey: yes
#dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
#dotfiles_files:
#  - .bash_profile
#  - .gitconfig
#  - .gitignore
##  - .inputrc
#  - .osx
#  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - git
  - go
  - gpg
  - iperf
  - packer
  - nmap
  - pv
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - fing
  - firefox
  - google-chrome
  - handbrake
  - kdiff3
  - macvim
  - sequel-pro
  - slack
  - sublime-text
  - vagrant
  - virtualbox
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
